/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoHospede;
import fatec.poo.control.DaoRecepcionista;
import fatec.poo.control.DaoRegistro;
import fatec.poo.control.DaoQuarto;
import fatec.poo.model.Hospede;
import fatec.poo.model.Quarto;
import fatec.poo.model.Recepcionista;
import fatec.poo.model.Registro;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author super
 */
public class GuiReservarLiberarQuarto extends javax.swing.JFrame {

    /**
     * Creates new form GuiReservarLiberarQuarto
     */
    public GuiReservarLiberarQuarto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnReservar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNQuarto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCPFHospede = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRegistroFuncional = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDataEntrada = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDataSaida = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValorHosp = new javax.swing.JTextField();
        txtRecepcionista = new javax.swing.JTextField();
        btnPesquisarRecepcionista = new javax.swing.JButton();
        btnPesquisarHospede = new javax.swing.JButton();
        txtHospede = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSituação = new javax.swing.JButton();
        txtSituação = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Hospedagem");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.setFocusPainted(false);
        btnLiberar.setMaximumSize(new java.awt.Dimension(99, 20));
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setMaximumSize(new java.awt.Dimension(99, 20));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.setFocusPainted(false);
        btnReservar.setMaximumSize(new java.awt.Dimension(99, 20));
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Registro Funcional");

        txtNQuarto.setEnabled(false);

        jLabel3.setText("CPF Hóspede");
        jLabel3.setToolTipText("");

        try {
            txtCPFHospede.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFHospede.setEnabled(false);

        jLabel4.setText("N°. Quarto");
        jLabel4.setToolTipText("");

        txtRegistroFuncional.setEnabled(false);

        jLabel5.setText("Data Entrada");
        jLabel5.setToolTipText("");

        try {
            txtDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataEntrada.setEnabled(false);

        jLabel6.setText("Data Saida");
        jLabel6.setToolTipText("");

        try {
            txtDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataSaida.setEnabled(false);

        jLabel7.setText("Valor Hospedagem");
        jLabel7.setToolTipText("");

        txtValorHosp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtValorHosp.setEnabled(false);

        txtRecepcionista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtRecepcionista.setEnabled(false);

        btnPesquisarRecepcionista.setText("...");
        btnPesquisarRecepcionista.setEnabled(false);
        btnPesquisarRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarRecepcionistaActionPerformed(evt);
            }
        });

        btnPesquisarHospede.setText("...");
        btnPesquisarHospede.setEnabled(false);
        btnPesquisarHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarHospedeActionPerformed(evt);
            }
        });

        txtHospede.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtHospede.setEnabled(false);

        jLabel8.setText("Situação");

        btnSituação.setText("...");
        btnSituação.setEnabled(false);
        btnSituação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSituaçãoActionPerformed(evt);
            }
        });

        txtSituação.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtSituação.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setMaximumSize(new java.awt.Dimension(99, 20));
        btnConsultar.setMinimumSize(new java.awt.Dimension(99, 23));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCPFHospede, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addComponent(txtDataEntrada)
                        .addComponent(txtDataSaida)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRegistroFuncional, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(txtNQuarto))
                            .addGap(76, 76, 76)))
                    .addComponent(txtValorHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisarRecepcionista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisarHospede)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSituação)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSituação, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRegistroFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarRecepcionista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCPFHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarHospede))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSituação)
                    .addComponent(txtSituação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtValorHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        registro = null;
        hospede = null;
        recepcionista = null;
        quarto = null;
        try {
            
            if(!txtCodigo.getText().matches("\\d")){
                txtCodigo.setText("");
                txtCodigo.requestFocus();
                JOptionPane.showMessageDialog(null, "Por favor, digite um Código(Número Inteiro).");
                
            }
            else{
                registro = daoRegistro.consultar(Integer.parseInt(txtCodigo.getText()));
                
                if(registro == null){
                    btnConsultar.setEnabled(false);
                    btnReservar.setEnabled(true);
                    txtRegistroFuncional.setEnabled(true);
                    btnPesquisarRecepcionista.setEnabled(true);
                    txtRegistroFuncional.requestFocus();
                }
                else{
                    btnConsultar.setEnabled(false);
                    hospede = registro.getHospede();
                    recepcionista = registro.getRecepcionista();
                    quarto = registro.getQuarto();
                    
                    
                    txtRegistroFuncional.setText(String.valueOf(recepcionista.getRegFunc()));
                    txtRecepcionista.setText(recepcionista.getNome());
                    txtCPFHospede.setText(hospede.getCpf());
                    txtHospede.setText(hospede.getNome());
                    txtNQuarto.setText(String.valueOf(quarto.getNumero()));
                    System.out.println(quarto.isSituacao());
                    txtSituação.setText((quarto.isSituacao())?"Ocupado":"Disponível");
                    
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    txtDataEntrada.setText(String.valueOf(registro.getDataEntrada().format(formatter)));
                    
                    if(registro.getDataSaida()==null){
                        txtDataSaida.setEnabled(true);
                        btnLiberar.setEnabled(true);
                        txtDataSaida.requestFocus();
                    }
                    else
                        txtDataSaida.setText(String.valueOf(registro.getDataSaida()));
                }
            }

        } catch (Exception e) {
            txtCodigo.requestFocus();
            JOptionPane.showMessageDialog(null, "Algo Errado! \nErro: " + e, "Erro", JOptionPane.ERROR_MESSAGE);
            System.out.println("Erro: " + e.toString());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("","");
        
        conexao.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        conexao.setConnectionString("jdbc:ucanaccess://C:\\Users\\super\\Documents\\MeusProjetos\\Estudos_Java\\prjPOOErickLuizNicolas\\src\\fatec\\poo\\basedados\\BDPOO.accdb");
        
        
        daoRegistro = new DaoRegistro(conexao.conectar());
        daoRecepcionista = new DaoRecepcionista(conexao.conectar());
        daoQuarto = new DaoQuarto(conexao.conectar());
        daoHospede = new DaoHospede(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void btnPesquisarRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarRecepcionistaActionPerformed
        recepcionista = null;
        
        try{
            recepcionista = daoRecepcionista.consultar(Integer.parseInt(txtRegistroFuncional.getText()));
            
            if(recepcionista == null){
                txtRegistroFuncional.requestFocus();
                JOptionPane.showMessageDialog(null, "Recepcionista não cadastrado!");
            }else{
                txtRecepcionista.setText(recepcionista.getNome());
                txtRegistroFuncional.setEnabled(false);
                btnPesquisarRecepcionista.setEnabled(false);
                txtCPFHospede.setEnabled(true);
                btnPesquisarHospede.setEnabled(true);
                txtCPFHospede.requestFocus();
            }
        }catch(NumberFormatException e){
            txtRegistroFuncional.requestFocus();
            JOptionPane.showMessageDialog(null, "Por favor, digite um código válido(Número Inteiro).", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarRecepcionistaActionPerformed

    private void btnPesquisarHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarHospedeActionPerformed
        hospede = null;
        
        try{
            hospede = daoHospede.consultar(txtCPFHospede.getText());
            
            if(hospede == null){
                txtCPFHospede.requestFocus();
                JOptionPane.showMessageDialog(null, "Hospede não cadastrado!");
            }else{
                txtHospede.setText(hospede.getNome());
                txtCPFHospede.setEnabled(false);
                btnPesquisarHospede.setEnabled(false);
                txtNQuarto.setEnabled(true);
                btnSituação.setEnabled(true);
                txtNQuarto.requestFocus();
            }
        }catch(NumberFormatException e){
            txtRegistroFuncional.requestFocus();
            JOptionPane.showMessageDialog(null, "Por favor, digite um código válido(Número Inteiro).", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarHospedeActionPerformed

    private void btnSituaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSituaçãoActionPerformed
        quarto = null;
        
        try{
            quarto = daoQuarto.consultar(Integer.parseInt(txtNQuarto.getText()));
            
            if(quarto == null){
                txtNQuarto.requestFocus();
                JOptionPane.showMessageDialog(null, "Quarto não cadastrado!");
            }else{
                if(quarto.isSituacao()){
                    JOptionPane.showMessageDialog(null, "Quarto ocupado!");
                    txtNQuarto.setText("");
                    txtNQuarto.requestFocus();
                }
                else{
                    txtSituação.setText("Disponível");
                    txtNQuarto.setEnabled(false);
                    btnSituação.setEnabled(false);
                    txtDataEntrada.setEnabled(true);
                    btnReservar.setEnabled(true);
                    txtDataEntrada.requestFocus();
                }
            }
        }catch(NumberFormatException e){
            txtRegistroFuncional.requestFocus();
            JOptionPane.showMessageDialog(null, "Por favor, digite um código válido(Número Inteiro).", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSituaçãoActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        try{
            LocalDate dataEntrada = formatarData(txtDataEntrada.getText());
            if(txtDataEntrada.getText().replace("/", "")=="" || dataEntrada.isBefore(LocalDate.now())){
                JOptionPane.showMessageDialog(null, "Digite uma data válida", "Erro:", JOptionPane.ERROR_MESSAGE);
                txtDataEntrada.requestFocus();
            }
            else{
                registro = new Registro(Integer.parseInt(txtCodigo.getText()), dataEntrada, recepcionista);
                registro.reservarQuarto(hospede, quarto);
                daoRegistro.inserir(registro);

                txtCodigo.setText("");
                txtRegistroFuncional.setText("");
                txtRecepcionista.setText("");
                txtCPFHospede.setText("");
                txtHospede.setText("");
                txtNQuarto.setText("");
                txtSituação.setText("");
                txtDataEntrada.setText("");

                txtCodigo.requestFocus();

                btnReservar.setEnabled(false);
                btnConsultar.setEnabled(true);
                txtDataEntrada.setEnabled(false);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Algo Errado! \nErro: " + ex.toString(), "Erro:", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        LocalDate dataSaida = formatarData(txtDataSaida.getText());
        LocalDate dataEntrada = formatarData(txtDataEntrada.getText());
        if(txtDataSaida.getText().replace("/", "") == "" || dataSaida.isBefore(LocalDate.now()) || dataSaida.isBefore(dataEntrada)){
            JOptionPane.showMessageDialog(null, "Digite uma data válida", "Erro:", JOptionPane.ERROR_MESSAGE);
            txtDataSaida.requestFocus();
        }
        else{
            registro.setDataSaida(dataSaida);
            txtValorHosp.setText(String.valueOf(registro.liberarQuarto()));
            daoRegistro.alterar(registro);
            btnLiberar.setEnabled(false);
            txtDataSaida.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnLiberarActionPerformed

    private LocalDate formatarData(String dataText){
        LocalDate data = LocalDate.of(Integer.parseInt(dataText.substring(6)), 
        Integer.parseInt(dataText.substring(3,5)), 
        Integer.parseInt(dataText.substring(0,2)));
        
        return data;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnPesquisarHospede;
    private javax.swing.JButton btnPesquisarRecepcionista;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSituação;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField txtCPFHospede;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtDataEntrada;
    private javax.swing.JFormattedTextField txtDataSaida;
    private javax.swing.JTextField txtHospede;
    private javax.swing.JTextField txtNQuarto;
    private javax.swing.JTextField txtRecepcionista;
    private javax.swing.JTextField txtRegistroFuncional;
    private javax.swing.JTextField txtSituação;
    private javax.swing.JTextField txtValorHosp;
    // End of variables declaration//GEN-END:variables
    private Conexao conexao=null;
    private Registro registro = null;
    private DaoRegistro daoRegistro = null;
    private Hospede hospede=null;
    private DaoHospede daoHospede=null;
    private Quarto quarto =null;
    private DaoQuarto daoQuarto=null;
    private Recepcionista recepcionista=null;
    private DaoRecepcionista daoRecepcionista=null;
}
